# version: '3.8'

services:
  db:
    image: postgres:15
    container_name: bff-postgres-db
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres-db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "8000:80"
    volumes:
      - ./app:/app
    depends_on:
      - db

volumes:
  postgres_data: