version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: fastapi_user
      POSTGRES_PASSWORD: fastapi_pass
      POSTGRES_DB: fastapi_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    image: tiangolo/uvicorn-gunicorn-fastapi:python3.11
    env_file:
      - .env
    ports:
      - "8000:80"
    volumes:
      - ./app:/app
    depends_on:
      - db

volumes:
  postgres_data: