"""adding user keys

Revision ID: 03ff80d79056
Revises: fc54defcb149
Create Date: 2025-07-14 10:14:12.690215

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '03ff80d79056'
down_revision: Union[str, None] = 'fc54defcb149'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('my-keys',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('key_value', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=False),
    sa.Column('date_updated', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_my-keys_id'), 'my-keys', ['id'], unique=False)
    op.create_index(op.f('ix_my-keys_key_value'), 'my-keys', ['key_value'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_my-keys_key_value'), table_name='my-keys')
    op.drop_index(op.f('ix_my-keys_id'), table_name='my-keys')
    op.drop_table('my-keys')
    # ### end Alembic commands ###
