"""fixing database schema

Revision ID: 5c15fc91ef33
Revises: 
Create Date: 2025-07-20 12:48:25.563403

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c15fc91ef33'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('callbacks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=False),
    sa.Column('contact_period', sa.String(), nullable=False),
    sa.Column('contact_motive', sa.String(), nullable=False),
    sa.Column('observation', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=False),
    sa.Column('date_updated', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_callbacks_id'), 'callbacks', ['id'], unique=False)
    op.create_table('devices',
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('fbase_token', sa.String(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=False),
    sa.Column('date_updated', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('email')
    )
    op.create_index(op.f('ix_devices_email'), 'devices', ['email'], unique=False)
    op.create_index(op.f('ix_devices_fbase_token'), 'devices', ['fbase_token'], unique=True)
    op.create_table('feedback',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('comment', sa.String(), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=False),
    sa.Column('date_updated', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feedback_email'), 'feedback', ['email'], unique=False)
    op.create_index(op.f('ix_feedback_id'), 'feedback', ['id'], unique=False)
    op.create_table('my-keys',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_token', sa.String(length=128), nullable=False),
    sa.Column('key_value', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=64), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=False),
    sa.Column('date_updated', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_my-keys_id'), 'my-keys', ['id'], unique=False)
    op.create_index(op.f('ix_my-keys_user_token'), 'my-keys', ['user_token'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_my-keys_user_token'), table_name='my-keys')
    op.drop_index(op.f('ix_my-keys_id'), table_name='my-keys')
    op.drop_table('my-keys')
    op.drop_index(op.f('ix_feedback_id'), table_name='feedback')
    op.drop_index(op.f('ix_feedback_email'), table_name='feedback')
    op.drop_table('feedback')
    op.drop_index(op.f('ix_devices_fbase_token'), table_name='devices')
    op.drop_index(op.f('ix_devices_email'), table_name='devices')
    op.drop_table('devices')
    op.drop_index(op.f('ix_callbacks_id'), table_name='callbacks')
    op.drop_table('callbacks')
    # ### end Alembic commands ###
