"""adding tables

Revision ID: c2147c1414fa
Revises: 
Create Date: 2025-07-13 21:52:42.370818

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c2147c1414fa'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('devices',
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('fbase_token', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('email')
    )
    op.create_index(op.f('ix_devices_email'), 'devices', ['email'], unique=False)
    op.create_index(op.f('ix_devices_fbase_token'), 'devices', ['fbase_token'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_devices_fbase_token'), table_name='devices')
    op.drop_index(op.f('ix_devices_email'), table_name='devices')
    op.drop_table('devices')
    # ### end Alembic commands ###
