"""adding dates to devices

Revision ID: e5dc774b5af0
Revises: c2147c1414fa
Create Date: 2025-07-13 22:00:04.887442

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e5dc774b5af0'
down_revision: Union[str, None] = 'c2147c1414fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('devices', sa.Column('date_created', sa.DateTime(), nullable=False))
    op.add_column('devices', sa.Column('date_updated', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('devices', 'date_updated')
    op.drop_column('devices', 'date_created')
    # ### end Alembic commands ###
