"""adding callbacks

Revision ID: fc54defcb149
Revises: 805146e7b166
Create Date: 2025-07-13 22:25:05.444365

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fc54defcb149'
down_revision: Union[str, None] = '805146e7b166'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('callbacks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=False),
    sa.Column('contact_period', sa.String(), nullable=False),
    sa.Column('contact_motive', sa.String(), nullable=False),
    sa.Column('observation', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=False),
    sa.Column('date_updated', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_callbacks_id'), 'callbacks', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_callbacks_id'), table_name='callbacks')
    op.drop_table('callbacks')
    # ### end Alembic commands ###
