# services.py
from sqlalchemy.orm import Session
from app.models import User 
from app.routes.users.schemas import UserCreate
from passlib.context import CryptContext # For password hashing

# Initialize password hashing context
# This tells passlib to use the bcrypt hashing algorithm.
pwd_context = CryptContext(schemes=["bcrypt"], deprecated="auto")

def get_password_hash(password: str) -> str:
    """
    Hashes a plain-text password using bcrypt.
    """
    return pwd_context.hash(password)

def verify_password(plain_password: str, hashed_password: str) -> bool:
    """
    Verifies a plain-text password against a hashed password.
    """
    return pwd_context.verify(plain_password, hashed_password)

class UserService:
    """
    Service layer for User-related operations.
    Encapsulates database interactions and business logic.
    """

    def get_user_by_email(self, db: Session, email: str):
        """
        Retrieves a user from the database by their email address.
        """
        return db.query(User).filter(User.email == email).first()

    def create_user(self, db: Session, user: UserCreate):
        """
        Creates a new user in the database.
        Hashes the password before storing it.
        """
        # Hash the password
        hashed_password = get_password_hash(user.password)

        # Create a new User ORM object
        db_user = User(email=user.email, hashed_password=hashed_password)

        # Add the user to the session
        db.add(db_user)
        # Commit the transaction to save the user to the database
        db.commit()
        # Refresh the instance to load any new data generated by the database
        # (e.g., the auto-incremented 'id')
        db.refresh(db_user)
        return db_user